Repository d-coder111/The-Wizards-Sorting-Hat, pull requests merged in 2024-10, with the labels that each got.

#1 Adding details of the project and suggestions to improve the same.
  README.md
Labels: hacktoberfest-accepted

#3 Adding styles.css file
  styles.css
Labels: hacktoberfest-accepted

#4 Create script.js
  script.js
Labels: hacktoberfest-accepted

#11 Update contributorslist
  README.md
Labels: hacktoberfest-accepted

#12 Add detailed Hogwarts house descriptions and center home image
  README.md
  index.html
  script.js
  styles.css
Labels: hacktoberfest-accepted

#17 Update script.js after correcting sorted button logic
  script.js
Labels: hacktoberfest-accepted

#19 Added few more questions
  .vscode/settings.json
  index.html
Labels: hacktoberfest-accepted

#23 Add favicon
  icons/icon.png
  index.html
Labels: hacktoberfest-accepted

#25 Merge Code_Of_Conduct.md
  Code_of_conduct.md
Labels: hacktoberfest-accepted

#32 add logo-img and houese-img
  index.html
  styles.css
Labels: enhancement, hacktoberfest-accepted

#38 I have changed the CSS of quiz .
  script.js
  styles.css
Labels: enhancement, hacktoberfest-accepted

#42 Form style changes
  index.html
  styles.css
Labels: enhancement, hacktoberfest-accepted

#44 Add_Theme_options
  index.html
  script.js
  styles.css
Labels: good first issue, hacktoberfest-accepted

#48 Update script.js
  script.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#51 Add footer section with links, social media icons, and newsletter form (Issue: #50)
  assests/images/sorting-hat.png
  index.html
  script.js
  styles.css
Labels: enhancement, hacktoberfest-accepted, design

#36 Sounds added in updated file
  diagon_alley.mp3
  index.html
  protego-105518.mp3
  script.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#54 Highlight Selected Option to Differentiate from Unselected Ones #53
  index.html
  styles.css
Labels: enhancement, hacktoberfest-accepted

#59 Added the gif effect on quiz submission
  index.html
  script.js
  styles.css
Labels: enhancement, good first issue, hacktoberfest-accepted

#60 Added more spells, Added glow effect to them select buttons
  script.js
Labels: enhancement, hacktoberfest-accepted

#63 Design Updates
  README.md
  assests/images/clipart1985953.png
  assests/images/graybolt.png
  index.html
  script.js
  styles.css
Labels: enhancement, hacktoberfest-accepted, design

#71 Cursor replaced with Magic Wand
  assests/images/wand.png
  index.html
  script.js
  styles.css
Labels: enhancement, hacktoberfest-accepted, design

#73 Add floating button
  assests/images/upicon.png
  index.html
  script.js
  styles.css
Labels: enhancement, hacktoberfest-accepted, design

#79 Add Spell Representation with Emojis (closes #77)
  script.js
Labels: good first issue, hacktoberfest-accepted
